### ISSUE TITLE
项目如果使用了redux，app.js为空在部署模式下，dev模式下没问题

### ISSUE THREAD

**Issue by hanwenbo** [realywithoutname/mini-loader-plugin-demo#3]
项目如果使用了redux，app.js为空在部署模式下，dev模式下没问题

app.js文件是空的
如果去掉redux就可以
但是在dev模式下没问题
我猜是mode的bug

**Comment by hanwenbo** [comment]
无奈只能使用uglifyjs对项目进行压缩了
这样干好像redux速度会变慢，因为开发者工具提示了：
VM3721:1 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

**Comment by hanwenbo** [comment]
问题2：common.js过大如何处理呢？

![image](https://user-images.githubusercontent.com/5869741/62457766-081fb900-b7ae-11e9-8563-f90ed2b21a1d.png)

**Comment by realywithoutname** [comment]
设置 cachegroup 可以控制打包到 common.js 的文件

**Comment by hanwenbo** [comment]
cachegroup 文档里没有涉及 这是什么

**Comment by hanwenbo** [comment]
明白了 webpack cacheGroup可以设置分包

**Comment by hanwenbo** [comment]
好了，感谢库主  webpack 增加 concatenateModules:false即可
